# Fakes a deployment by waiting 10 seconds before sending a board event for deploy-complete
name: Deploy a release

on:
  repository_dispatch:
    types: [start-deployment]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo We are deploying
            - name: initiate start event
              uses: mmayer1/github-actions/initiateBoardEvent@main
              with:
                host: https://platform-dev.leankit.io
                apiToken: ${{ secrets.D03LEANKIT }}
                boardId: 10136774076
                eventName: deploy-started
            - run: |
                sleep 10
                echo Deployment is done
            - name: initiate end event
              uses: mmayer1/github-actions/initiateBoardEvent@main
              with:
                host: https://platform-dev.leankit.io
                apiToken: ${{ secrets.D03LEANKIT }}
                boardId: 10136774076
                eventName: deploy-complete
