# Sends the pr-merged event on a PR that has a card title including an ID in parens like (12345)
name: PR Merge

on:
    pull_request:
      types:
        - closed

jobs:
    send_event:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - id: getCardId
              name: get card id
              uses: mmayer1/github-actions/extractCardId@main
              with:
                inputText: ${{ github.event.pull_request.title }}
            - run: |
                echo The PR was merged ${{ steps.getCardId.outputs.cardId }}
            - name: trigger event
              uses: mmayer1/github-actions/triggerEvent@main
              with:
                host: https://platform-dev.leankit.io
                apiToken: ${{ secrets.D03LEANKIT }}
                boardId: 10136774076
                cardId: ${{ steps.getCardId.outputs.cardId }}
                eventName: pr-merged
